// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TeamspeakAnalytics.database.mssql;

namespace TeamspeakAnalytics.database.mssql.Migrations
{
    [DbContext(typeof(TS3AnalyticsDbContext))]
    partial class TS3AnalyticsDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.3-rtm-32065")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("TeamspeakAnalytics.database.mssql.Entities.TS3Client", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("ChangeDate");

                    b.Property<DateTime>("Created");

                    b.Property<int>("DatabaseId");

                    b.Property<DateTime>("LastConnected");

                    b.Property<string>("NickName");

                    b.Property<string>("TS3Plattform");

                    b.Property<string>("TS3Version");

                    b.Property<int>("TotalConnectionCount");

                    b.Property<string>("UniqueIdentifier")
                        .IsRequired()
                        .HasMaxLength(28);

                    b.HasKey("Id");

                    b.HasIndex("UniqueIdentifier")
                        .IsUnique();

                    b.ToTable("TS3Clients");
                });

            modelBuilder.Entity("TeamspeakAnalytics.database.mssql.Entities.TS3ClientConnection", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("ChannelId");

                    b.Property<Guid>("ClientGuid");

                    b.Property<TimeSpan>("IncactiveSince");

                    b.Property<DateTime>("TimeStampEnd");

                    b.Property<DateTime>("TimeStampStart");

                    b.HasKey("Id");

                    b.HasIndex("ClientGuid");

                    b.ToTable("TS3ClientConnection");
                });

            modelBuilder.Entity("TeamspeakAnalytics.database.mssql.Entities.User", b =>
                {
                    b.Property<Guid>("UserId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Password");

                    b.Property<string>("Username")
                        .IsRequired();

                    b.HasKey("UserId");

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("TeamspeakAnalytics.database.mssql.Entities.TS3ClientConnection", b =>
                {
                    b.HasOne("TeamspeakAnalytics.database.mssql.Entities.TS3Client", "TS3Client")
                        .WithMany("TS3ClientConnections")
                        .HasForeignKey("ClientGuid")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
